version: "3.7"

volumes:
  data: {}

services:
  relay:
    image: scsibug/nostr-rs-relay:0.8.13
    ports:
      - 5000:8080
    volumes:
      - data:/usr/src/app/db
  app:
    build: .
    depends_on:
      - relay
    environment:
      CACHE_RELAY: relay:8080
    ports:
      - 8080:80
